{{- if .Values.gitWebhookProxy.ingress.enabled }}
{{- if semverCompare "<1.15-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: extensions/v1beta1
{{- else if and (semverCompare ">=1.15-0" .Capabilities.KubeVersion.GitVersion) (semverCompare "<1.19-0" .Capabilities.KubeVersion.GitVersion) -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: networking.k8s.io/v1
{{- end }}
kind: Ingress
metadata:
{{- if .Values.gitWebhookProxy.ingress.annotations }}
  annotations:
{{ toYaml .Values.gitWebhookProxy.ingress.annotations | indent 4 }}
{{- end }}
  labels:
{{ include "gitwebhookproxy.labels.stakater" . | indent 4 }}
{{ include "gitwebhookproxy.labels.chart" . | indent 4 }}
{{- if .Values.gitWebhookProxy.useCustomName }}
  name: {{ .Values.gitWebhookProxy.customName }}
{{- else }}
  name: {{ template "gitwebhookproxy.name" . }}
{{- end }}
spec:
  rules:
  - host: {{ .Values.gitWebhookProxy.ingress.host }}
    http:
      paths:
      {{- if semverCompare "<1.19-0" .Capabilities.KubeVersion.GitVersion -}} 
      - backend:
        {{- if .Values.gitWebhookProxy.useCustomName }}
          serviceName: {{ .Values.gitWebhookProxy.customName }}
        {{- else }}
          serviceName: {{ template "gitwebhookproxy.name" . }}
        {{- end }}
          servicePort: 80
      {{- else -}}
      - pathType: ImplementationSpecific
        backend:
          service:
          {{- if .Values.gitWebhookProxy.useCustomName }}
            name: {{ .Values.gitWebhookProxy.customName }}
          {{- else }}
            name: {{ template "gitwebhookproxy.name" . }}
          {{- end }}
            port:
              number: 80
      {{- end }}
  tls:
  - hosts:
    - {{ .Values.gitWebhookProxy.ingress.host }}
  {{- if .Values.gitWebhookProxy.ingress.tlsSecretName }}
    secretName: {{ .Values.gitWebhookProxy.ingress.tlsSecretName }}
  {{- end }}
{{- end }}
